#!/bin/bash
set -e

if [ -z "$GIT_URL"] ; then
  GIT_URL="https://github.com/michaelsevilla/JXIO.git"
fi

cd /
if [ ! -d /JXIO/.git ]; then
    git clone $GIT_URL
fi

cd /JXIO
git pull
git clean -fd
./build.sh

